### ISSUE TITLE
tag tip ui will disappear after selecting a blessing

### ISSUE THREAD

**Issue by Kooluve** [kjossul/NeowBlessings#1]
tag tip ui will disappear after selecting a blessing, only reload blind select menu it can reappear, like defeat a blind or sl
![1](https://github.com/kjossul/NeowBlessings/assets/56555833/044c13a5-3008-409f-a3aa-77711f426da4)
![2](https://github.com/kjossul/NeowBlessings/assets/56555833/3e7eac9e-a9b2-4dd5-aa07-ebd96d25355c)

**Comment by kjossul** [comment]
Thanks for opening this issue! I was aware of it but didn't find a fix yet. I suspected it had something to do with the `G.SETTINGS.paused` flag but in theory that should be set to `false` when the overlay disappears. I'll try to dig into what happens when you get back into the blind menu to see if there's a solution.

**Comment by typhoonbro** [comment]
In my last [PR](https://github.com/kjossul/NeowBlessings/pull/3) I commented the line that sets the `G.SETTINGS.paused` to `true`, The UI flow of choosing a blessing didn't seemed to be affected by it. Said that, the bug is not present anymore.

**Comment by typhoonbro** [comment]
Problem solved in #3

**Comment by typhoonbro** [comment]
Problem solved in #3
